rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-head

script: "rake test"

notifications:
  disable: true
