source 'https://rubygems.org'

# Specify your gem's dependencies in editor.gemspec
gemspec

# Development
# gem 'shoperb-liquid', path: '../gems/liquid', require: false
# gem 'shoperb-solid', path: '../gems/solid', require: false
# gem 'shoperb_mounter', path: '../gems/mounter', require: false
# gem 'shoperb_mounter', github: 'shoperb/mounter', ref: '34d24feeb8', require: false


gem 'rb-fsevent', '~> 0.9.1'

gem 'shoperb_mounter', :path => '../mounter'

gem 'liquid', github: 'Shopify/liquid'