source "https://rubygems.org"

gem "shoperb-theme-editor", git: "git@code.perfectline.co:shoperb/theme-generator.git"
gem "liquid", github: "Shopify/liquid", ref: "f15d24509d0f429f56284da527e6186708a27725"
gem "sprockets", github: "sstephenson/sprockets", ref: "2d429001907a29382e9fc5fb1326391bbae4feb9"